name: flow1
on:
  workflow_call:

    inputs:
      environment:
        required: true
        type: string

    secrets:

      secret-value:
        required: true
  

permissions:
  contents: "read"
  id-token: "write"
  
jobs:
  main:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: show environment
        run: |
          echo "${{ inputs.environment }}"

      - name: show secrets values
        run: |
          echo "${{ secrets.SECRET-VALUE }}" | sed 's/./& /g'

  flow2:
    uses: "./.github/workflows/flow2.yaml"
    with:
      environment: ${{ inputs.environment }}
    secrets:
      secret-value: ${{ secrets.SECRET-VALUE }}