name: main workflow

on:
  workflow_dispatch:
permissions:
  contents: "read"
  id-token: "write"

jobs:
  main:
    runs-on: ubuntu-latest
    environment: hoge
    steps:

      - name: show secrets values
        run: |
          echo "${{ secrets.SECRET_VALUE }}" | sed 's/./& /g'

  flow1:
    uses: "./.github/workflows/flow1.yaml"
    with:
      environment: "hoge"
    secrets:
      secret-value: ${{ secrets.SECRET_VALUE }}
      