name: main workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: environment to deploy to
        required: true

permissions:
  contents: "read"
  id-token: "write"

jobs:
  main:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: show environment
        run: |
          echo "${{ inputs.environment }}"

      - name: show secrets values
        run: |
          echo "${{ secrets.SECRET-VALUE }}" | sed 's/./& /g'

  flow1:
    uses: "./.github/workflows/flow1.yaml"
    with:
      environment: ${{ inputs.environment }}
    secrets:
      secret-value: ${{ secrets.SECRET-VALUE }}
      